# Generated by Django 4.2.4 on 2023-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0003_productitem_delete_productitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
