# Generated by Django 4.2.4 on 2023-10-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0004_alter_productitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
