# Generated by Django 4.2.4 on 2023-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0005_delete_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('dis_price', models.IntegerField()),
                ('act_price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
