# Generated by Django 4.2.4 on 2023-10-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0007_productitem_details_productitem_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='details',
        ),
    ]
