# Generated by Django 4.2.4 on 2023-10-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0008_remove_productitem_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='d1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='productitem',
            name='d2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='productitem',
            name='d3',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='productitem',
            name='d4',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
