# Generated by Django 4.2.4 on 2023-10-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0009_productitem_d1_productitem_d2_productitem_d3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('mobile', models.PositiveBigIntegerField()),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
