# Generated by Django 4.2.4 on 2023-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0010_customerdetail_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='name',
            new_name='nam',
        ),
    ]
