# Generated by Django 4.2.4 on 2023-10-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0011_rename_name_customerdetail_nam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='nam',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='address',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='mail',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='mobile',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
