# Generated by Django 4.2.4 on 2023-10-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0012_remove_customerdetail_nam_customerdetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
    ]
