# Generated by Django 4.2.4 on 2023-10-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0014_alter_customerdetail_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='address',
            field=models.CharField(max_length=2000),
        ),
    ]
