# Generated by Django 4.2.4 on 2023-10-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0015_alter_customerdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
