# Generated by Django 4.2.4 on 2023-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0020_alter_customerdetail_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='mobile',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
