# Generated by Django 4.2.5 on 2023-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADSHIP_APP', '0024_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PNumber',
            field=models.CharField(max_length=10),
        ),
    ]
